services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:2yGp2cL7+FIB98HIpN4v3W4OGtMbapkhTMZqrdmTSkg=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: dpg-d1fausidbo4c739qujig-a
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: it-dev-portfolio
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: RbtDKWrzpvuAcvgBoVBXT66MNnkPGM8r
